language: python

python:
  - 3.6
  # - 3.7

os: linux
dist: xenial
sudo: required

env:
  global:
    - TEST_CMD='py.test'
    - MPI_TEST_CMD='python'
    - the_world_is_flat=false
  matrix:
    - MPI=mpich
    - MPI=openmpi

matrix:
  include:

    - python: 3.6
      env:
        - MPI=openmpi
        - TEST_CMD='py.test --cov --cov-append'
        # - MPI_TEST_CMD='coverage run -a' # if we can get coverage working...
        - RUN_COVERAGE=true

before_install:
  - sh ci/travis/install-mpi.sh $MPI

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install cython
  - pip install mpi4py>=3.0.0
  - pip install joblib
  - pip install dill
  - pip install coveralls
  - pip install alabaster
  - pip install -vvv .

before_script:
  - if [[ "$MPI" == "mpich" ]]; then P=2; else P=5; fi

script:
  - SCHWIMMBAD_TEST_MPI=1 mpiexec -n $P python $PWD/schwimmbad/tests/test_mpi.py
  - SCHWIMMBAD_TEST_MPI=1 mpiexec -n $P python $PWD/schwimmbad/tests/test_mpi_with_dill.py
  - SCHWIMMBAD_TEST_MPIASYNC=1 mpiexec -n $P python -m mpi4py.futures $PWD/schwimmbad/tests/test_mpi.py
  - $TEST_CMD

after_success:
  - if [ "$RUN_COVERAGE" = true ] ; then
        python -m coverage combine;
        coveralls;
    fi
